name: Postman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  collection-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/unix.sh" | sh
      - name: Login to Postman
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run collection
        run: postman collection run 52538155-eac25291-0f3c-42b2-8ca8-a81d1d56f4e6 --report-events
